# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('original_amt', models.FloatField(null=True)),
                ('current_amt', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roastdate', models.DateTimeField(auto_now_add=True)),
                ('target_temp', models.IntegerField(null=True)),
                ('weight_before', models.FloatField(null=True)),
                ('weight_after', models.FloatField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('heater', models.IntegerField(null=True)),
                ('drawfan', models.IntegerField(null=True)),
                ('scrollfan', models.IntegerField(null=True)),
                ('drum', models.IntegerField(null=True)),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roasts.Bean')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roasts.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='RoastLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoastSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data point timestamp', models.DateTimeField(auto_now_add=True)),
                ('heater', models.IntegerField()),
                ('drawfan', models.IntegerField()),
                ('scrollfan', models.IntegerField()),
                ('drum', models.IntegerField()),
                ('env_temp', models.IntegerField()),
                ('bean_temp', models.IntegerField()),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roasts.Roast')),
            ],
        ),
        migrations.AddField(
            model_name='roast',
            name='roast_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roasts.RoastLevel'),
        ),
    ]
