# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roasts.Customer'),
        ),
    ]
